<?php 

include_once $_SERVER["DOCUMENT_ROOT"] . "/app/controller/access.controller.php";

$head = <<<'CSS'

	<style>
		#content {
			width: 80%;
			margin: auto;
		}
	</style>
CSS;

$title = "FAWN :: Terms of Use";
include $_SERVER["DOCUMENT_ROOT"] . "/includes/header.php"; ?>

<h2>TERMS OF USE OF FAWN: Forging A Worldwide Network, LLC </h2>

<h3>1. Your Acceptance of Terms of Use</h3>

<p>FAWN: Forging a Worldwide Network, LLC (“,” “Our,” “We,” “Us”) provides its services, described below, to you (“User,” “You,” “Your”) through its website located at                      .com and through its mobile applications and related services, (collectively, such services, including any new features and applications, and the Website referred to as (“Services”)), subject to the following Terms of Use (as amended from time to time, these “Terms of Use”). By accessing or using the Services, You expressly agree to these Terms of Use and any other legal notices, policies or guidelines located on or within the Services. If You do not agree to any of the terms and conditions of these Terms of Use or other notices or guidelines, please do not use the Services and exit now.</p>

<p>You may be required to register with FAWN: Forging a Worldwide Network, LLC in order to communicate with other registered members, and access and use certain Services or features. If You choose to register, You must meet the eligibility requirements and further read these Terms of Use and indicate Your acceptance of them.</p>

<p>You affirm that You are more than 16 years of age and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms of Use, and to abide by and comply with these Terms of Use. The Services are not intended for children under the age of thirteen (13).</p>

<p>If You are under 13 years of age, then please do not use the Services and exit now.</p>

<h3>2. Important Legal Information Regarding Privacy</h3>

<p>You agree that You have read, understood and accept this privacy policy. The Privacy Policy explains FAWN: Forging a Worldwide Network, LLC’s collection of personal and non-personal information from You when using the Services and Our use and sharing of such personal and non-personal information.</p>

<h3>3. FAWN: Forging a Worldwide Network, LLC Services</h3>

<p>A. These Terms of Use apply to all users of the Services, including users who are also registered members. The FAWN: Forging a Worldwide Network, LLC Content, defined below, is provided as a courtesy to Our users and is intended for personal, informational, educational and non-commercial purposes only. Any other use is a violation of the Terms of Use and Copyright law and will be prosecuted to the fullest extent allowed by law. </p>

<p>B. The Services may contain links to institutional or other third-party web sites or applications that are not owned or controlled by FAWN: Forging a Worldwide Network, LLC. FAWN: Forging a Worldwide Network, LLC has no control over, and assumes no responsibility for the products, services, content, privacy policies or practices of any institutional or third-party web site or application. In addition, FAWN: Forging a Worldwide Network, LLC is unable and unwilling to censor or edit the content of any institutional or third-party web site or application. FAWN: Forging a Worldwide Network, LLC is not involved in any transactions between You and any third party whose products and/or services are listed on the Services. By accessing or using the Services, You expressly relieve FAWN: Forging a Worldwide Network, LLC from any and all liability arising from Your use of any linked institutional or third-party web site or application. Accordingly, We encourage You to be aware when You leave Our Services and to read the terms and conditions and privacy policy of each web site or application that You access or use. If You decide to access any other web sites or applications linked to or from Our Services, You acknowledge sole responsibility, assume all risks, and relieve FAWN: Forging a Worldwide Network, LLC of any liability from Your use thereof. Any questions, complaints, or claims related to any product or service provided by a third party on the Services should be directed to the applicable third party.</p>

<p>C. FAWN: Forging a Worldwide Network, LLC encourages You to carefully choose the information You submit, post, or provide to others using the Services or Services features (e.g., comments, blogs, video chat sessions, mobile application, and promotion entries). Any conversations or information You have or share with others using features that are available below, may be accessible and viewable by all other users or by other registered members of the Services. FAWN: Forging a Worldwide Network, LLC does not control, or have any knowledge of the content of any communication(s) spread by the use or functions of the Services, such as the video chat feature or the posting of User Submissions. The content of the communication is entirely the responsibility of the person from whom such content originated.</p>

<p>D. FAWN: Forging a Worldwide Network, LLC reserves the right to remove, edit or reject any User Submissions, defined below, at any time, in its sole discretion. Furthermore, FAWN: Forging a Worldwide Network, LLC may restrict, suspend or terminate any user’s access to or use of all or any part of the Services or its features at any time, for any or no reason, with Our without notice and with no liability to FAWN: Forging a Worldwide Network, LLC whatsoever.</p>

<h3>4. Services Access</h3>

<p>A. FAWN: Forging a Worldwide Network, LLC hereby grants You a limited, personal, non-assignable, non-exclusive, fully revocable license to use and access the Services and its features as set forth in these Terms of Use, provided that: (i) You will not distribute any part of the Services (other than User Submissions owned by You) in any medium without FAWN: Forging a Worldwide Network, LLC’s prior written authorization; (ii) You will not alter, disassemble, decompile, reverse engineer or otherwise modify any part of the Services other than as may be reasonably necessary to use the Services for its intended purpose; and (iii) You will otherwise comply with these Terms of Use. You agree not to delete, change or modify in any way the copyright notices, trademarks or other intellectual property contained on the Services.</p>

<p>B. In order to access many features of the Services, You will have to create a registered member account and access Our Services through a third party platform that requires You to have a login name and password (e.g, Facebook). FAWN: Forging a Worldwide Network, LLC does not store or have access to Your password, but as part of such integration, the third party platform will provide us with access to certain information that You have provided to such third party platform, and We will use, store and disclose such information in accordance with Our Privacy Policy. However, please remember that the manner in which the third party platforms use, store and disclose Your information is governed solely by the policies of such third parties, and FAWN: Forging a Worldwide Network, LLC shall have no liability or responsibility for the privacy practices or other actions of any third party site or service that may be enabled or accessed within the Services. You may never use another member’s account or share Your account with any other user or entity. When creating Your account, You agree that You will provide current, complete and accurate information, and You agree that you will update Your account information as necessary to keep it current, complete and accurate. You are solely responsible for the activity that occurs on Your account. You must notify FAWN: Forging a Worldwide Network, LLC immediately of any breach of security or unauthorized use of Your account by contacting Us at FAWN: Forging a Worldwide Network, LLC.</p>

<p>C. You agree that You will not use the Services and the features offered through the Services (i) in connection with any commercial activities and/or sales, including without limitation advertising, contests, sweepstakes or pyramid schemes, without FAWN: Forging a Worldwide Network, LLC’s prior written consent, (ii) to promote information that You know is false or misleading or to promote illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous, (iii) to further or promote any criminal activity or enterprise, including without limitation, harassment, stalking, copyright infringement, copyright, trademark or other intellectual property infringement, or theft of trade secrets, (iv) to solicit personally identifiable information for commercial or unlawful purposes, (v) to advertise to, solicit, or sell to any person without their prior explicit consent, (vi) to harvest or collect personally identifiable information such as e-mail addresses, account names, passwords or other contact information of users or members for purposes of sending unsolicited communications or commercial solicitations. In order to protect third parties and other users from such prohibited conduct, FAWN: Forging a Worldwide Network, LLC reserves the right to restrict, in its sole discretion, communications which a user may send through the Services. </p>

<p>D. The Services include certain services that are available via a mobile device, including (i) the ability to upload User Submissions, defined below, to the User via a mobile device, (ii) the ability to browse the Serviced from a mobile device and (iii) the ability to access the Services and Promotions through an application downloaded and installed on a mobile device (collectively, the “Mobile Services”). To the extent You access the Services through a mobile device, Your wireless service carrier’s standard charges, data rates and other fees may apply. In addition, downloading, installing, or using certain Mobile Services may be prohibited or restricted by Your carrier, and not all Mobile Services may work with all carriers or devices. By using the Mobile Services, You agree that We may communicate with You regarding FAWN: Forging a Worldwide Network, LLC, Promotions, and other entities related to any of Our Services or Promotions by SMS, MMS, text message or other electronic means to Your mobile device and that certain information about Your usage of the Mobile Services may be communicated to Us. In the event You change or deactivate Your mobile telephone number, You agree to promptly update your FAWN: Forging a Worldwide Network, LLC account information to ensure that Your messages are not sent to the person that acquires your old number.</p>

<h3>5. User Submissions</h3>

<p>A. The Services may permit the submission of certain promotion entries, user-generated text, information, data, video, chats, audio, photographs, files or other content to or through the Services (“User Submissions”) and the hosting, sharing, transmission and/or publishing of such User Submissions. User Submissions may be used, distributed and published by FAWN: Forging a Worldwide Network, LLC and viewed by both general users and registered members of the Services. You understand that FAWN: Forging a Worldwide Network, LLC does not guarantee any confidentiality with respect to any User Submissions.</p>

<p>B. You shall be solely responsible for Your User Submissions and the consequences of submitting, posting or publishing them. In connection with User Submissions, You affirm, represent, and warrant that: (i) You own or have the necessary licenses, rights, consents, and permissions to use and authorize FAWN: Forging a Worldwide Network, LLC to use all copyrights, trademarks, trade secrets, patents or any other proprietary or personal rights in and to Your User Submissions to enable inclusion and use of such User Submissions in the manner contemplated by the Services and these Terms of Use; (ii) submitting, posting or publishing Your User Submission on or through the Services does not and will not violate any confidentiality obligations between You and any person or organization or the privacy rights, publicity rights or other rights of any person; and (iii) You have the written consent, release, and/or permission of each and every identifiable person or organization in Your User Submission to use the name or likeness of each and every such identifiable person or organization to enable inclusion and use of the User Submissions in the manner contemplated by the Services and these Terms of Use. You further affirm, represent and warrant that Your User Submissions are not defamatory or libelous in any manner whatsoever. </p>

<p>C. You will retain all ownership rights in Your User Submissions.  By submitting a User Submission to FAWN: Forging a Worldwide Network, LLC and permitting it to be viewed, posted or published on or through the Services, You hereby grant to FAWN: Forging a Worldwide Network, LLC a perpetual, worldwide, non-exclusive, royalty-free, fully paid up, sub-licensable and transferable license to use, post and store User Submissions on or through Services and servers and publish, distribute and display such User Submissions in connection with the Services and FAWN: Forging a Worldwide Network, LLC’s (and its successor’s) business, including without limitation the right to distribute such User Submissions to other users and third parties. You agree that this license includes the right for FAWN: Forging a Worldwide Network, LLC to provide, promote, and improve the Services and to make User Submissions submitted to or through the Services available to other companies, organizations or individuals who partner with FAWN: Forging a Worldwide Network, LLC for the syndication, broadcast, distribution or publication of such User Submissions on other media and services, subject to Our Terms of Use for such Content use.  No compensation shall be made to You with respect to the Content or User Submissions that You post, transmit, or otherwise make available through Services. 
We may modify or adapt Your Content in order to transmit, display or distribute it over computer networks and in various media and/or make changes to Your Content as are necessary to conform and adapt that Content to any requirements or limitations of any networks, devices, services or media.  You are responsible for Your use of the Services, for any Content You provide, and for any consequences thereof, including the use of Your Content by other users and Our third party partners.  You further hereby waive any and all moral rights and all rights of a similar nature in any jurisdiction in Your User Submission. </p>

<p>D. In connection with any User Submissions, You further agree that you will not: (i) submit or publish falsehoods, misrepresentations or statements that could damage FAWN: Forging a Worldwide Network, LLC or any third party; (ii) submit material that is false, misleading, inaccurate, derogatory, unlawful, obscene, defamatory, contains nudity, libelous, threatening, sexually explicit or pornographic, harassing, hateful, intimidating, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense of any federal, state or local law, give rise to civil liability, violate any law, or is otherwise inappropriate or objectionable; (iii) post advertisements or business solicitations, including any “junk mail” or “spam”; (iv) impersonate another person, institution or organization or falsely state or otherwise misrepresent Yourself, Your age or Your affiliation with any third party, organization, institution or person; (v) upload, post, store or otherwise make available any virus, bug, Trojan horse or other computer file or program that is capable of destroying, interrupting or interfering with or limiting the functionality of the Services or any server, computer hardware, software or equipment. FAWN: Forging a Worldwide Network, LLC does not endorse any User Submission or any opinion, recommendation, or advice expressed therein. FAWN: Forging a Worldwide Network, LLC reserves the right to remove FAWN: Forging a Worldwide Network, LLC Content and User Submissions without prior notice. FAWN: Forging a Worldwide Network, LLC also reserves the right to decide whether FAWN: Forging a Worldwide Network, LLC Content or a User Submission is appropriate and complies with these Terms of Use for violations other than copyright infringement and violations of intellectual property law, such as, but not limited to, trademark infringement, violations of rights of publicity or privacy, obscene or defamatory material, or excessive length. FAWN: Forging a Worldwide Network, LLC may remove such User Submissions and/or terminate a user’s access for accessing or distributing such material in violation of these Terms of Use at any time, without prior notice and at its sole discretion.</p>

<p>E. You understand that when accessing and using the Services, You will be exposed to User Submissions and third party information from a variety of sources and that FAWN: Forging a Worldwide Network, LLC is not responsible for the accuracy, usefulness, safety or intellectual property rights of or relating to such User Submissions and third party information. You further understand and acknowledge that You may be exposed to User Submissions that are inaccurate, offensive, indecent, or objectionable, and You agree to waive, and hereby do waive, any legal or equitable rights or remedies You have or may have against FAWN: Forging a Worldwide Network, LLC with respect thereto.</p>

<h3>6. Intellectual Property Policy</h3>

<p>The content on and in the Services, except all User Submissions (“FAWN: Forging a Worldwide Network, LLC Content”) is owned by or licensed to FAWN: Forging a Worldwide Network, LLC, subject to copyright and other intellectual property rights under United States and foreign laws and international conventions. FAWN: Forging a Worldwide Network, LLC respects the intellectual property rights of its respective owners and requires Users of its Services to do the same.  Users are expressly prohibited from any use of intellectual property owned or licensed to FAWN: Forging a Worldwide Network, LLC in any manner without FAWN: Forging a Worldwide Network, LLC’s prior written consent. Additionally, intellectual property owned or licensed by FAWN: Forging a Worldwide Network, LLC or any of its affiliates (vendors) may not be reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for any other purposes whatsoever without the prior written consent of the respective owner. FAWN: Forging a Worldwide Network, LLC reserves all rights not expressly granted in and to the Services and the FAWN: Forging a Worldwide Network, LLC Content. You agree to not engage in the use, copying, or distribution of any of the FAWN: Forging a Worldwide Network, LLC Content other than as expressly permitted herein or as reasonably necessary to use the Services for its intended purpose. You agree not to circumvent, disable or otherwise interfere with security related features of the Services or features that prevent or restrict use or copying of any FAWN: Forging a Worldwide Network, LLC Content or User Submissions or enforce limitations on use of the Services or the FAWN: Forging a Worldwide Network, LLC Content and User Submissions.</p>

<h3>7. Copyright Policy Specifically</h3>

<h4>A. Notification</h4>

<p>If You are a copyright owner or an agent thereof and believe that any User Submission or other FAWN: Forging a Worldwide Network, LLC Content infringes upon Your copyright, You may submit a written notification pursuant to the Digital Millennium Copyright Act (“DMCA”) (see 17 U.S.C. 512(c)(3) for further information) by providing Our Copyright Agent listed below with the following information: (i) an electronic or physical signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; (ii) a description of the copyrighted work claimed to have been infringed or if multiple copyrighted works are covered by a notification, a representative list of such works on or in the Services; (iii) a description of the location on the Services of the allegedly infringing material(s); (iv) Your address, telephone number, and e-mail address; (v) a written statement that You have a good faith belief that use of the material(s) in the manner complained of is not authorized by the copyright owner, its agent, or the law; and (vi) a written statement that the information in the notification is accurate, and under penalty of perjury, that You are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</p>

<p>FAWN: Forging a Worldwide Network, LLC designated Copyright Agent for notice of claims of infringement is:
[ADDRESS]  </p>

<p>Only notices of alleged copyright infringement should go to the Copyright Agent; any other feedback, comments, requests for technical support, and other communications should be directed to FAWN: Forging a Worldwide Network, LLC’ customer service at FAWN: Forging a Worldwide Network, LLC. You acknowledge that if You fail to comply with all of the notice requirements of the DMCA, Your notice may not be valid. </p>

<h4>B. Counter-Notification.</h4> 

<p>If You believe that Your User Submission was removed but was not infringing, or that You have the appropriate rights from the copyright owner or third party, or pursuant to the law, to post and use the material in Your User Submission, You may send a counter notification containing the following information to the Copyright Agent: (i) Your physical or electronic signature; (ii) identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or disabled; (iii) a statement (under penalty of perjury) that You have a good faith belief that the content was removed or disabled as a result of mistake or a misidentification of the material; and Your name, address, telephone number, and e-mail address, along with a statement that You consent to the jurisdiction of the court identified in the Governing Law & Jurisdiction section below along with a statement that You will accept service of process from the person who provided notification of the alleged infringement.</p>

<p>If a counter notification is received by the Copyright Agent, FAWN: Forging a Worldwide Network, LLC shall send a copy of such counter notification to the original notifying party. The original notifying party shall have ten (10) business days to file an action for copyright infringement and seek a court order against the content provider or user posting such material. If no such infringement action is filed within such 10 business days, FAWN: Forging a Worldwide Network, LLC may, in its sole discretion, reinstate the removed material or cease disabling such material. </p>

<p>C. In accordance with the DMCA and other applicable law, FAWN: Forging a Worldwide Network, LLC shall, in appropriate circumstances, terminate access, at FAWN: Forging a Worldwide Network, LLC’ sole discretion, of any registered member that FAWN: Forging a Worldwide Network, LLC finds to be a repeat infringer of others copyrights. FAWN: Forging a Worldwide Network, LLC may also, in its sole discretion, limit or fully terminate access to the Site of any user infringing the intellectual property rights of others, regardless of whether such user is repeat offender or not.</p>

<h3>8. Member Disputes</h3>

<p>You are solely responsible for Your interactions with other users or members of the Services and any disputes that may arise.</p>

<h3>9. Warranty Disclaimer</h3>

<p>You agree that Your access and use of the Services shall be at Your sole risk. The Services, the FAWN: Forging a Worldwide Network, LLC Content, User Submissions and any services or features made available on or through the Services are provided on an “as is” and “as available” basis. FAWN: Forging a Worldwide Network, LLC does not make and disclaims any and all express and implied warranties and representations, including but not limited to any implied warranty or fitness for a particular purpose, with regard to the Services, the FAWN: Forging a Worldwide Network, LLC Content, User Submissions or any services of features provided on or through the Services, to the fullest extent permitted by law. Without limiting the foregoing, FAWN: Forging a Worldwide Network, LLC does not represent or warrant that: (i) the Services will be accurate, reliable, uninterrupted, secure or error-free; (ii) defects in the Services will be corrected; or (iii) the Services or the server that makes it available are free of viruses or other harmful components; (iv) whether the Services will meet Your requirements or be available on an uninterrupted, secure, or error-free basis.  FAWN: Forging a Worldwide Network, LLC does not warrant, endorse, guarantee, or assume responsibility for any product or service advertised or offered by any institution or third party through the Services or any hyperlinked web site or application. No advice or information, whether oral or written, obtained through the Services, will create any warranty not expressly made herein.</p>

<h3>10. Limitation of Liability</h3>

<p>In no event shall FAWN: Forging a Worldwide Network, LLC, its officers, directors, employees, affiliates, subsidiaries, agents and other partners be liable, whether in contract, warranty, tort (including negligence), or any other form of liability, for: (i) any indirect, special, incidental, consequential or punitive damages that may be incurred by You; (ii) any loss of data, income, business or profits or revenues (whether direct or indirect) that may be incurred by You; and (iii) any claim, damage, or loss which may be incurred by You as a result of (a) the availability or unavailability of the Services and/or any other third-party web sites or applications, (b) any reliance placed by You on any advertising, products, services or other content or materials on, or available from, the Services or any third-party web site or application; (iii) any of Your transactions with third parties or other users, including but not limited to, any defamatory, offensive, illegal, or unauthorized conduct or use of Your submissions. The limitations on FAWN: Forging a Worldwide Network, LLC’ liability to You above shall apply whether or not FAWN: Forging a Worldwide Network, LLC has been advised of the possibility of such losses or damages arising. The foregoing limitation of liability shall apply to the fullest extent permitted by law in the applicable jurisdiction. In no event shall the aggregate liability of FAWN: Forging a Worldwide Network, LLC exceed One Hundred U.S. Dollars (US $100.00).</p>

<h3>11. Indemnity</h3>

<p>You agree to indemnify and hold harmless FAWN: Forging a Worldwide Network, LLC, its officers, employees, agents, subsidiaries, affiliates and other partners, from and against any claims, actions, demands, liabilities or settlements, including without limitation reasonable legal and accounting fees, resulting from, or alleged to result from, Your conduct using the Services, Your violation of these Terms of Use or, Your violation any other legal notices or guidelines.</p>

<h3>12. Modifications &amp; Notifications</h3>

<p>We reserve the right to revise these Terms of Use from time to time and posting such revisions on Our website.  Any modifications of these Terms of Use become effective immediately upon post, display, or other notification method selected in the sole discretion of FAWN: Forging a Worldwide Network, LLC.  As such, You agree to review the Terms of Use periodically and become aware of modifications.  By accessing or using the Site, You agree to be bound by all of the Terms of Use as posted at the time of Your access or use.  If any change that We make is not acceptable to You, promptly stop using the Services. Any access or use by You of the Services after any changes to Our Terms of Use become effective will signify Your agreement to be bound by those changes.</p>

<p>It is FAWN: Forging a Worldwide Network, LLC  policy to provide notifications, whether such notifications are required by law or are for marketing or other business related purposes, to Our constituents or web site users, via e-mail notice, written or hard copy notice, or through posting of such notice on Our Site, www.fawnworldwide.org as determined by Us in Our sole discretion.  Notwithstanding the foregoing, We reserve the right to determine the form and means of providing notifications to Our constituents or web site users. </p>

<h3>13. Assignment</h3>

<p>FAWN: Forging a Worldwide Network, LLC reserves the right to assign any rights and licenses granted hereunder however no such rights and licenses may be transferred or assigned by You.</p>

<h3>14. Governing Law &amp; Jurisdiction</h3>

<p>These Terms of Use and any action related thereto shall be governed by the laws of New York and the applicable federal laws of the United States of America without regard to any conflict of law provisions. All disputes arising under, or in any way connected with membership in or use of the Services, shall be litigated exclusively in the state and federal courts in the State of New York, and in no other court or jurisdiction. You hereby submit to jurisdiction and venue in such courts and waive any objection as to inconvenient forum.</p>

<h3>15. Entire Agreement</h3>

<p>These Terms of Use, along with Promotions & Giveaway Terms of Use, and Our Privacy Policy are the entire and exclusive agreement between FAWN: Forging a Worldwide Network, LLC and You regarding the Services (excluding any services for which You have a separate agreement with FAWN: Forging a Worldwide Network, LLC that is explicitly in addition or in place of these Terms), and these Terms supersede and replace any prior agreements between FAWN: Forging a Worldwide Network, LLC and You regarding the Services. No other person or company will be third party beneficiaries to the Terms.</p>

<h3>16. Waiver &amp; Severability</h3>

<p>If any provision of these Terms of Use is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms of Use, which shall remain in full force and effect. FAWN: Forging a Worldwide Network, LLC’ failure to assert any right or provision under these Terms of Use shall not constitute a waiver of such right or provision and no waiver of any term of these Terms of Use shall be deemed a further or continuing waiver of such term or any other term.</p>

<h3>17. Termination &amp; Exclusion</h3>

<p>We reserve the right, in Our sole discretion, to revoke, terminate or suspend any and all privileges associated with accessing or using the Services for any reason or for no reason whatsoever including improper use of the Services or failure to comply with these Terms of Use or any other notices or guidelines, and to take any other action We deem appropriate.  Upon termination, Your license to use Services shall terminate immediately.</p>

<h3>18. User Suggestions</h3>

<p>You acknowledge and agree that any questions, comments, suggestions, ideas, feedback or other information provided by You to FAWN: Forging a Worldwide Network, LLC are not confidential and You grant us a worldwide, royalty-free license to distribute, publish, modify, edit or otherwise use Your submissions. FAWN: Forging a Worldwide Network, LLC shall be entitled to the unrestricted use and dissemination of these submissions for any purpose, commercial or otherwise without any acknowledgement of or compensation to You.</p>

<h3>19. Questions; Comments</h3>

<p>If You have any questions or comments about the Services or become aware of misuse of the Services by any person, please contact US at info@fawnworldwide.org.</p>


</div>

<?php include $_SERVER["DOCUMENT_ROOT"] . "/includes/footer.php"; ?>